// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

#include "message.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG
namespace Update_ShooterTest {
constexpr KcpWelcome_S_C::KcpWelcome_S_C(
  ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized)
  : slotid_(0){}
struct KcpWelcome_S_CDefaultTypeInternal {
  constexpr KcpWelcome_S_CDefaultTypeInternal()
    : _instance(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized{}) {}
  ~KcpWelcome_S_CDefaultTypeInternal() {}
  union {
    KcpWelcome_S_C _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT KcpWelcome_S_CDefaultTypeInternal _KcpWelcome_S_C_default_instance_;
constexpr PlayerInfo_S_TO_C::PlayerInfo_S_TO_C(
  ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized)
  : x_(0)
  , y_(0)
  , angle_(0)
  , id_(0){}
struct PlayerInfo_S_TO_CDefaultTypeInternal {
  constexpr PlayerInfo_S_TO_CDefaultTypeInternal()
    : _instance(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized{}) {}
  ~PlayerInfo_S_TO_CDefaultTypeInternal() {}
  union {
    PlayerInfo_S_TO_C _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PlayerInfo_S_TO_CDefaultTypeInternal _PlayerInfo_S_TO_C_default_instance_;
constexpr UpdateInfo_S_TO_C::UpdateInfo_S_TO_C(
  ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized)
  : playerinfos_()
  , lastprocessedframeid_(0)
  , inputbuffersize_(0){}
struct UpdateInfo_S_TO_CDefaultTypeInternal {
  constexpr UpdateInfo_S_TO_CDefaultTypeInternal()
    : _instance(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized{}) {}
  ~UpdateInfo_S_TO_CDefaultTypeInternal() {}
  union {
    UpdateInfo_S_TO_C _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT UpdateInfo_S_TO_CDefaultTypeInternal _UpdateInfo_S_TO_C_default_instance_;
constexpr KcpConnectReq_C_S::KcpConnectReq_C_S(
  ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized){}
struct KcpConnectReq_C_SDefaultTypeInternal {
  constexpr KcpConnectReq_C_SDefaultTypeInternal()
    : _instance(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized{}) {}
  ~KcpConnectReq_C_SDefaultTypeInternal() {}
  union {
    KcpConnectReq_C_S _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT KcpConnectReq_C_SDefaultTypeInternal _KcpConnectReq_C_S_default_instance_;
constexpr PlayerInput_C_TO_S::PlayerInput_C_TO_S(
  ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized)
  : frameid_(0)
  , w_(false)
  , s_(false)
  , a_(false)
  , d_(false)
  , rotation_(0)
  , id_(0){}
struct PlayerInput_C_TO_SDefaultTypeInternal {
  constexpr PlayerInput_C_TO_SDefaultTypeInternal()
    : _instance(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized{}) {}
  ~PlayerInput_C_TO_SDefaultTypeInternal() {}
  union {
    PlayerInput_C_TO_S _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PlayerInput_C_TO_SDefaultTypeInternal _PlayerInput_C_TO_S_default_instance_;
}  // namespace Update_ShooterTest
static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_message_2eproto[5];
static const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* file_level_enum_descriptors_message_2eproto[1];
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_message_2eproto = nullptr;

const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_message_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::Update_ShooterTest::KcpWelcome_S_C, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::Update_ShooterTest::KcpWelcome_S_C, slotid_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::Update_ShooterTest::PlayerInfo_S_TO_C, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::Update_ShooterTest::PlayerInfo_S_TO_C, x_),
  PROTOBUF_FIELD_OFFSET(::Update_ShooterTest::PlayerInfo_S_TO_C, y_),
  PROTOBUF_FIELD_OFFSET(::Update_ShooterTest::PlayerInfo_S_TO_C, angle_),
  PROTOBUF_FIELD_OFFSET(::Update_ShooterTest::PlayerInfo_S_TO_C, id_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::Update_ShooterTest::UpdateInfo_S_TO_C, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::Update_ShooterTest::UpdateInfo_S_TO_C, lastprocessedframeid_),
  PROTOBUF_FIELD_OFFSET(::Update_ShooterTest::UpdateInfo_S_TO_C, playerinfos_),
  PROTOBUF_FIELD_OFFSET(::Update_ShooterTest::UpdateInfo_S_TO_C, inputbuffersize_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::Update_ShooterTest::KcpConnectReq_C_S, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::Update_ShooterTest::PlayerInput_C_TO_S, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::Update_ShooterTest::PlayerInput_C_TO_S, frameid_),
  PROTOBUF_FIELD_OFFSET(::Update_ShooterTest::PlayerInput_C_TO_S, w_),
  PROTOBUF_FIELD_OFFSET(::Update_ShooterTest::PlayerInput_C_TO_S, s_),
  PROTOBUF_FIELD_OFFSET(::Update_ShooterTest::PlayerInput_C_TO_S, a_),
  PROTOBUF_FIELD_OFFSET(::Update_ShooterTest::PlayerInput_C_TO_S, d_),
  PROTOBUF_FIELD_OFFSET(::Update_ShooterTest::PlayerInput_C_TO_S, rotation_),
  PROTOBUF_FIELD_OFFSET(::Update_ShooterTest::PlayerInput_C_TO_S, id_),
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::Update_ShooterTest::KcpWelcome_S_C)},
  { 7, -1, -1, sizeof(::Update_ShooterTest::PlayerInfo_S_TO_C)},
  { 17, -1, -1, sizeof(::Update_ShooterTest::UpdateInfo_S_TO_C)},
  { 26, -1, -1, sizeof(::Update_ShooterTest::KcpConnectReq_C_S)},
  { 32, -1, -1, sizeof(::Update_ShooterTest::PlayerInput_C_TO_S)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::Update_ShooterTest::_KcpWelcome_S_C_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::Update_ShooterTest::_PlayerInfo_S_TO_C_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::Update_ShooterTest::_UpdateInfo_S_TO_C_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::Update_ShooterTest::_KcpConnectReq_C_S_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::Update_ShooterTest::_PlayerInput_C_TO_S_default_instance_),
};

const char descriptor_table_protodef_message_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\rmessage.proto\022\022Update_ShooterTest\" \n\016K"
  "cpWelcome_S_C\022\016\n\006slotid\030\001 \001(\005\"D\n\021PlayerI"
  "nfo_S_TO_C\022\t\n\001x\030\001 \001(\002\022\t\n\001y\030\002 \001(\002\022\r\n\005angl"
  "e\030\003 \001(\002\022\n\n\002id\030\004 \001(\005\"\206\001\n\021UpdateInfo_S_TO_"
  "C\022\034\n\024lastProcessedFrameID\030\001 \001(\005\022:\n\013playe"
  "rInfos\030\002 \003(\0132%.Update_ShooterTest.Player"
  "Info_S_TO_C\022\027\n\017inputBufferSize\030\003 \001(\005\"\023\n\021"
  "KcpConnectReq_C_S\"o\n\022PlayerInput_C_TO_S\022"
  "\017\n\007frameID\030\001 \001(\005\022\t\n\001w\030\002 \001(\010\022\t\n\001s\030\003 \001(\010\022\t"
  "\n\001a\030\004 \001(\010\022\t\n\001d\030\005 \001(\010\022\020\n\010rotation\030\006 \001(\002\022\n"
  "\n\002id\030\007 \001(\005*r\n\004TYPE\022\025\n\021updateInfo_S_TO_C\020"
  "\000\022\024\n\020kcpConnectionReq\020\001\022\016\n\nkcpWelcome\020\002\022"
  "\025\n\021playerInfo_S_TO_C\020\003\022\026\n\022playerInput_C_"
  "TO_S\020\004b\006proto3"
  ;
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_message_2eproto_once;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_message_2eproto = {
  false, false, 534, descriptor_table_protodef_message_2eproto, "message.proto", 
  &descriptor_table_message_2eproto_once, nullptr, 0, 5,
  schemas, file_default_instances, TableStruct_message_2eproto::offsets,
  file_level_metadata_message_2eproto, file_level_enum_descriptors_message_2eproto, file_level_service_descriptors_message_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable* descriptor_table_message_2eproto_getter() {
  return &descriptor_table_message_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY static ::PROTOBUF_NAMESPACE_ID::internal::AddDescriptorsRunner dynamic_init_dummy_message_2eproto(&descriptor_table_message_2eproto);
namespace Update_ShooterTest {
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* TYPE_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_message_2eproto);
  return file_level_enum_descriptors_message_2eproto[0];
}
bool TYPE_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
      return true;
    default:
      return false;
  }
}


// ===================================================================

class KcpWelcome_S_C::_Internal {
 public:
};

KcpWelcome_S_C::KcpWelcome_S_C(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor();
  if (!is_message_owned) {
    RegisterArenaDtor(arena);
  }
  // @@protoc_insertion_point(arena_constructor:Update_ShooterTest.KcpWelcome_S_C)
}
KcpWelcome_S_C::KcpWelcome_S_C(const KcpWelcome_S_C& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  slotid_ = from.slotid_;
  // @@protoc_insertion_point(copy_constructor:Update_ShooterTest.KcpWelcome_S_C)
}

void KcpWelcome_S_C::SharedCtor() {
slotid_ = 0;
}

KcpWelcome_S_C::~KcpWelcome_S_C() {
  // @@protoc_insertion_point(destructor:Update_ShooterTest.KcpWelcome_S_C)
  if (GetArenaForAllocation() != nullptr) return;
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

inline void KcpWelcome_S_C::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void KcpWelcome_S_C::ArenaDtor(void* object) {
  KcpWelcome_S_C* _this = reinterpret_cast< KcpWelcome_S_C* >(object);
  (void)_this;
}
void KcpWelcome_S_C::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void KcpWelcome_S_C::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void KcpWelcome_S_C::Clear() {
// @@protoc_insertion_point(message_clear_start:Update_ShooterTest.KcpWelcome_S_C)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  slotid_ = 0;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* KcpWelcome_S_C::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // int32 slotid = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 8)) {
          slotid_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* KcpWelcome_S_C::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:Update_ShooterTest.KcpWelcome_S_C)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 slotid = 1;
  if (this->_internal_slotid() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt32ToArray(1, this->_internal_slotid(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Update_ShooterTest.KcpWelcome_S_C)
  return target;
}

size_t KcpWelcome_S_C::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Update_ShooterTest.KcpWelcome_S_C)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // int32 slotid = 1;
  if (this->_internal_slotid() != 0) {
    total_size += ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32SizePlusOne(this->_internal_slotid());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData KcpWelcome_S_C::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSizeCheck,
    KcpWelcome_S_C::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*KcpWelcome_S_C::GetClassData() const { return &_class_data_; }

void KcpWelcome_S_C::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to,
                      const ::PROTOBUF_NAMESPACE_ID::Message& from) {
  static_cast<KcpWelcome_S_C *>(to)->MergeFrom(
      static_cast<const KcpWelcome_S_C &>(from));
}


void KcpWelcome_S_C::MergeFrom(const KcpWelcome_S_C& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:Update_ShooterTest.KcpWelcome_S_C)
  GOOGLE_DCHECK_NE(&from, this);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_slotid() != 0) {
    _internal_set_slotid(from._internal_slotid());
  }
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void KcpWelcome_S_C::CopyFrom(const KcpWelcome_S_C& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Update_ShooterTest.KcpWelcome_S_C)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool KcpWelcome_S_C::IsInitialized() const {
  return true;
}

void KcpWelcome_S_C::InternalSwap(KcpWelcome_S_C* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(slotid_, other->slotid_);
}

::PROTOBUF_NAMESPACE_ID::Metadata KcpWelcome_S_C::GetMetadata() const {
  return ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(
      &descriptor_table_message_2eproto_getter, &descriptor_table_message_2eproto_once,
      file_level_metadata_message_2eproto[0]);
}

// ===================================================================

class PlayerInfo_S_TO_C::_Internal {
 public:
};

PlayerInfo_S_TO_C::PlayerInfo_S_TO_C(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor();
  if (!is_message_owned) {
    RegisterArenaDtor(arena);
  }
  // @@protoc_insertion_point(arena_constructor:Update_ShooterTest.PlayerInfo_S_TO_C)
}
PlayerInfo_S_TO_C::PlayerInfo_S_TO_C(const PlayerInfo_S_TO_C& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&x_, &from.x_,
    static_cast<size_t>(reinterpret_cast<char*>(&id_) -
    reinterpret_cast<char*>(&x_)) + sizeof(id_));
  // @@protoc_insertion_point(copy_constructor:Update_ShooterTest.PlayerInfo_S_TO_C)
}

void PlayerInfo_S_TO_C::SharedCtor() {
::memset(reinterpret_cast<char*>(this) + static_cast<size_t>(
    reinterpret_cast<char*>(&x_) - reinterpret_cast<char*>(this)),
    0, static_cast<size_t>(reinterpret_cast<char*>(&id_) -
    reinterpret_cast<char*>(&x_)) + sizeof(id_));
}

PlayerInfo_S_TO_C::~PlayerInfo_S_TO_C() {
  // @@protoc_insertion_point(destructor:Update_ShooterTest.PlayerInfo_S_TO_C)
  if (GetArenaForAllocation() != nullptr) return;
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

inline void PlayerInfo_S_TO_C::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void PlayerInfo_S_TO_C::ArenaDtor(void* object) {
  PlayerInfo_S_TO_C* _this = reinterpret_cast< PlayerInfo_S_TO_C* >(object);
  (void)_this;
}
void PlayerInfo_S_TO_C::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void PlayerInfo_S_TO_C::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void PlayerInfo_S_TO_C::Clear() {
// @@protoc_insertion_point(message_clear_start:Update_ShooterTest.PlayerInfo_S_TO_C)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&x_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&id_) -
      reinterpret_cast<char*>(&x_)) + sizeof(id_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* PlayerInfo_S_TO_C::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // float x = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 13)) {
          x_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else
          goto handle_unusual;
        continue;
      // float y = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 21)) {
          y_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else
          goto handle_unusual;
        continue;
      // float angle = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 29)) {
          angle_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else
          goto handle_unusual;
        continue;
      // int32 id = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 32)) {
          id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* PlayerInfo_S_TO_C::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:Update_ShooterTest.PlayerInfo_S_TO_C)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // float x = 1;
  if (!(this->_internal_x() <= 0 && this->_internal_x() >= 0)) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteFloatToArray(1, this->_internal_x(), target);
  }

  // float y = 2;
  if (!(this->_internal_y() <= 0 && this->_internal_y() >= 0)) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteFloatToArray(2, this->_internal_y(), target);
  }

  // float angle = 3;
  if (!(this->_internal_angle() <= 0 && this->_internal_angle() >= 0)) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteFloatToArray(3, this->_internal_angle(), target);
  }

  // int32 id = 4;
  if (this->_internal_id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt32ToArray(4, this->_internal_id(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Update_ShooterTest.PlayerInfo_S_TO_C)
  return target;
}

size_t PlayerInfo_S_TO_C::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Update_ShooterTest.PlayerInfo_S_TO_C)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // float x = 1;
  if (!(this->_internal_x() <= 0 && this->_internal_x() >= 0)) {
    total_size += 1 + 4;
  }

  // float y = 2;
  if (!(this->_internal_y() <= 0 && this->_internal_y() >= 0)) {
    total_size += 1 + 4;
  }

  // float angle = 3;
  if (!(this->_internal_angle() <= 0 && this->_internal_angle() >= 0)) {
    total_size += 1 + 4;
  }

  // int32 id = 4;
  if (this->_internal_id() != 0) {
    total_size += ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32SizePlusOne(this->_internal_id());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData PlayerInfo_S_TO_C::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSizeCheck,
    PlayerInfo_S_TO_C::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*PlayerInfo_S_TO_C::GetClassData() const { return &_class_data_; }

void PlayerInfo_S_TO_C::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to,
                      const ::PROTOBUF_NAMESPACE_ID::Message& from) {
  static_cast<PlayerInfo_S_TO_C *>(to)->MergeFrom(
      static_cast<const PlayerInfo_S_TO_C &>(from));
}


void PlayerInfo_S_TO_C::MergeFrom(const PlayerInfo_S_TO_C& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:Update_ShooterTest.PlayerInfo_S_TO_C)
  GOOGLE_DCHECK_NE(&from, this);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (!(from._internal_x() <= 0 && from._internal_x() >= 0)) {
    _internal_set_x(from._internal_x());
  }
  if (!(from._internal_y() <= 0 && from._internal_y() >= 0)) {
    _internal_set_y(from._internal_y());
  }
  if (!(from._internal_angle() <= 0 && from._internal_angle() >= 0)) {
    _internal_set_angle(from._internal_angle());
  }
  if (from._internal_id() != 0) {
    _internal_set_id(from._internal_id());
  }
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void PlayerInfo_S_TO_C::CopyFrom(const PlayerInfo_S_TO_C& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Update_ShooterTest.PlayerInfo_S_TO_C)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool PlayerInfo_S_TO_C::IsInitialized() const {
  return true;
}

void PlayerInfo_S_TO_C::InternalSwap(PlayerInfo_S_TO_C* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(PlayerInfo_S_TO_C, id_)
      + sizeof(PlayerInfo_S_TO_C::id_)
      - PROTOBUF_FIELD_OFFSET(PlayerInfo_S_TO_C, x_)>(
          reinterpret_cast<char*>(&x_),
          reinterpret_cast<char*>(&other->x_));
}

::PROTOBUF_NAMESPACE_ID::Metadata PlayerInfo_S_TO_C::GetMetadata() const {
  return ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(
      &descriptor_table_message_2eproto_getter, &descriptor_table_message_2eproto_once,
      file_level_metadata_message_2eproto[1]);
}

// ===================================================================

class UpdateInfo_S_TO_C::_Internal {
 public:
};

UpdateInfo_S_TO_C::UpdateInfo_S_TO_C(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned),
  playerinfos_(arena) {
  SharedCtor();
  if (!is_message_owned) {
    RegisterArenaDtor(arena);
  }
  // @@protoc_insertion_point(arena_constructor:Update_ShooterTest.UpdateInfo_S_TO_C)
}
UpdateInfo_S_TO_C::UpdateInfo_S_TO_C(const UpdateInfo_S_TO_C& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      playerinfos_(from.playerinfos_) {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&lastprocessedframeid_, &from.lastprocessedframeid_,
    static_cast<size_t>(reinterpret_cast<char*>(&inputbuffersize_) -
    reinterpret_cast<char*>(&lastprocessedframeid_)) + sizeof(inputbuffersize_));
  // @@protoc_insertion_point(copy_constructor:Update_ShooterTest.UpdateInfo_S_TO_C)
}

void UpdateInfo_S_TO_C::SharedCtor() {
::memset(reinterpret_cast<char*>(this) + static_cast<size_t>(
    reinterpret_cast<char*>(&lastprocessedframeid_) - reinterpret_cast<char*>(this)),
    0, static_cast<size_t>(reinterpret_cast<char*>(&inputbuffersize_) -
    reinterpret_cast<char*>(&lastprocessedframeid_)) + sizeof(inputbuffersize_));
}

UpdateInfo_S_TO_C::~UpdateInfo_S_TO_C() {
  // @@protoc_insertion_point(destructor:Update_ShooterTest.UpdateInfo_S_TO_C)
  if (GetArenaForAllocation() != nullptr) return;
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

inline void UpdateInfo_S_TO_C::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void UpdateInfo_S_TO_C::ArenaDtor(void* object) {
  UpdateInfo_S_TO_C* _this = reinterpret_cast< UpdateInfo_S_TO_C* >(object);
  (void)_this;
}
void UpdateInfo_S_TO_C::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void UpdateInfo_S_TO_C::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void UpdateInfo_S_TO_C::Clear() {
// @@protoc_insertion_point(message_clear_start:Update_ShooterTest.UpdateInfo_S_TO_C)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  playerinfos_.Clear();
  ::memset(&lastprocessedframeid_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&inputbuffersize_) -
      reinterpret_cast<char*>(&lastprocessedframeid_)) + sizeof(inputbuffersize_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* UpdateInfo_S_TO_C::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // int32 lastProcessedFrameID = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 8)) {
          lastprocessedframeid_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // repeated .Update_ShooterTest.PlayerInfo_S_TO_C playerInfos = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 18)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_playerinfos(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<18>(ptr));
        } else
          goto handle_unusual;
        continue;
      // int32 inputBufferSize = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 24)) {
          inputbuffersize_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* UpdateInfo_S_TO_C::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:Update_ShooterTest.UpdateInfo_S_TO_C)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 lastProcessedFrameID = 1;
  if (this->_internal_lastprocessedframeid() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt32ToArray(1, this->_internal_lastprocessedframeid(), target);
  }

  // repeated .Update_ShooterTest.PlayerInfo_S_TO_C playerInfos = 2;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->_internal_playerinfos_size()); i < n; i++) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(2, this->_internal_playerinfos(i), target, stream);
  }

  // int32 inputBufferSize = 3;
  if (this->_internal_inputbuffersize() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt32ToArray(3, this->_internal_inputbuffersize(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Update_ShooterTest.UpdateInfo_S_TO_C)
  return target;
}

size_t UpdateInfo_S_TO_C::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Update_ShooterTest.UpdateInfo_S_TO_C)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .Update_ShooterTest.PlayerInfo_S_TO_C playerInfos = 2;
  total_size += 1UL * this->_internal_playerinfos_size();
  for (const auto& msg : this->playerinfos_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  // int32 lastProcessedFrameID = 1;
  if (this->_internal_lastprocessedframeid() != 0) {
    total_size += ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32SizePlusOne(this->_internal_lastprocessedframeid());
  }

  // int32 inputBufferSize = 3;
  if (this->_internal_inputbuffersize() != 0) {
    total_size += ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32SizePlusOne(this->_internal_inputbuffersize());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData UpdateInfo_S_TO_C::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSizeCheck,
    UpdateInfo_S_TO_C::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*UpdateInfo_S_TO_C::GetClassData() const { return &_class_data_; }

void UpdateInfo_S_TO_C::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to,
                      const ::PROTOBUF_NAMESPACE_ID::Message& from) {
  static_cast<UpdateInfo_S_TO_C *>(to)->MergeFrom(
      static_cast<const UpdateInfo_S_TO_C &>(from));
}


void UpdateInfo_S_TO_C::MergeFrom(const UpdateInfo_S_TO_C& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:Update_ShooterTest.UpdateInfo_S_TO_C)
  GOOGLE_DCHECK_NE(&from, this);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  playerinfos_.MergeFrom(from.playerinfos_);
  if (from._internal_lastprocessedframeid() != 0) {
    _internal_set_lastprocessedframeid(from._internal_lastprocessedframeid());
  }
  if (from._internal_inputbuffersize() != 0) {
    _internal_set_inputbuffersize(from._internal_inputbuffersize());
  }
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void UpdateInfo_S_TO_C::CopyFrom(const UpdateInfo_S_TO_C& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Update_ShooterTest.UpdateInfo_S_TO_C)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool UpdateInfo_S_TO_C::IsInitialized() const {
  return true;
}

void UpdateInfo_S_TO_C::InternalSwap(UpdateInfo_S_TO_C* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  playerinfos_.InternalSwap(&other->playerinfos_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(UpdateInfo_S_TO_C, inputbuffersize_)
      + sizeof(UpdateInfo_S_TO_C::inputbuffersize_)
      - PROTOBUF_FIELD_OFFSET(UpdateInfo_S_TO_C, lastprocessedframeid_)>(
          reinterpret_cast<char*>(&lastprocessedframeid_),
          reinterpret_cast<char*>(&other->lastprocessedframeid_));
}

::PROTOBUF_NAMESPACE_ID::Metadata UpdateInfo_S_TO_C::GetMetadata() const {
  return ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(
      &descriptor_table_message_2eproto_getter, &descriptor_table_message_2eproto_once,
      file_level_metadata_message_2eproto[2]);
}

// ===================================================================

class KcpConnectReq_C_S::_Internal {
 public:
};

KcpConnectReq_C_S::KcpConnectReq_C_S(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase(arena, is_message_owned) {
  // @@protoc_insertion_point(arena_constructor:Update_ShooterTest.KcpConnectReq_C_S)
}
KcpConnectReq_C_S::KcpConnectReq_C_S(const KcpConnectReq_C_S& from)
  : ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:Update_ShooterTest.KcpConnectReq_C_S)
}





const ::PROTOBUF_NAMESPACE_ID::Message::ClassData KcpConnectReq_C_S::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::CopyImpl,
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::MergeImpl,
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*KcpConnectReq_C_S::GetClassData() const { return &_class_data_; }







::PROTOBUF_NAMESPACE_ID::Metadata KcpConnectReq_C_S::GetMetadata() const {
  return ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(
      &descriptor_table_message_2eproto_getter, &descriptor_table_message_2eproto_once,
      file_level_metadata_message_2eproto[3]);
}

// ===================================================================

class PlayerInput_C_TO_S::_Internal {
 public:
};

PlayerInput_C_TO_S::PlayerInput_C_TO_S(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor();
  if (!is_message_owned) {
    RegisterArenaDtor(arena);
  }
  // @@protoc_insertion_point(arena_constructor:Update_ShooterTest.PlayerInput_C_TO_S)
}
PlayerInput_C_TO_S::PlayerInput_C_TO_S(const PlayerInput_C_TO_S& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&frameid_, &from.frameid_,
    static_cast<size_t>(reinterpret_cast<char*>(&id_) -
    reinterpret_cast<char*>(&frameid_)) + sizeof(id_));
  // @@protoc_insertion_point(copy_constructor:Update_ShooterTest.PlayerInput_C_TO_S)
}

void PlayerInput_C_TO_S::SharedCtor() {
::memset(reinterpret_cast<char*>(this) + static_cast<size_t>(
    reinterpret_cast<char*>(&frameid_) - reinterpret_cast<char*>(this)),
    0, static_cast<size_t>(reinterpret_cast<char*>(&id_) -
    reinterpret_cast<char*>(&frameid_)) + sizeof(id_));
}

PlayerInput_C_TO_S::~PlayerInput_C_TO_S() {
  // @@protoc_insertion_point(destructor:Update_ShooterTest.PlayerInput_C_TO_S)
  if (GetArenaForAllocation() != nullptr) return;
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

inline void PlayerInput_C_TO_S::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void PlayerInput_C_TO_S::ArenaDtor(void* object) {
  PlayerInput_C_TO_S* _this = reinterpret_cast< PlayerInput_C_TO_S* >(object);
  (void)_this;
}
void PlayerInput_C_TO_S::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void PlayerInput_C_TO_S::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void PlayerInput_C_TO_S::Clear() {
// @@protoc_insertion_point(message_clear_start:Update_ShooterTest.PlayerInput_C_TO_S)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&frameid_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&id_) -
      reinterpret_cast<char*>(&frameid_)) + sizeof(id_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* PlayerInput_C_TO_S::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // int32 frameID = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 8)) {
          frameid_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // bool w = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 16)) {
          w_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // bool s = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 24)) {
          s_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // bool a = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 32)) {
          a_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // bool d = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 40)) {
          d_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // float rotation = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 53)) {
          rotation_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else
          goto handle_unusual;
        continue;
      // int32 id = 7;
      case 7:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 56)) {
          id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* PlayerInput_C_TO_S::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:Update_ShooterTest.PlayerInput_C_TO_S)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 frameID = 1;
  if (this->_internal_frameid() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt32ToArray(1, this->_internal_frameid(), target);
  }

  // bool w = 2;
  if (this->_internal_w() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteBoolToArray(2, this->_internal_w(), target);
  }

  // bool s = 3;
  if (this->_internal_s() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteBoolToArray(3, this->_internal_s(), target);
  }

  // bool a = 4;
  if (this->_internal_a() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteBoolToArray(4, this->_internal_a(), target);
  }

  // bool d = 5;
  if (this->_internal_d() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteBoolToArray(5, this->_internal_d(), target);
  }

  // float rotation = 6;
  if (!(this->_internal_rotation() <= 0 && this->_internal_rotation() >= 0)) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteFloatToArray(6, this->_internal_rotation(), target);
  }

  // int32 id = 7;
  if (this->_internal_id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt32ToArray(7, this->_internal_id(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Update_ShooterTest.PlayerInput_C_TO_S)
  return target;
}

size_t PlayerInput_C_TO_S::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Update_ShooterTest.PlayerInput_C_TO_S)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // int32 frameID = 1;
  if (this->_internal_frameid() != 0) {
    total_size += ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32SizePlusOne(this->_internal_frameid());
  }

  // bool w = 2;
  if (this->_internal_w() != 0) {
    total_size += 1 + 1;
  }

  // bool s = 3;
  if (this->_internal_s() != 0) {
    total_size += 1 + 1;
  }

  // bool a = 4;
  if (this->_internal_a() != 0) {
    total_size += 1 + 1;
  }

  // bool d = 5;
  if (this->_internal_d() != 0) {
    total_size += 1 + 1;
  }

  // float rotation = 6;
  if (!(this->_internal_rotation() <= 0 && this->_internal_rotation() >= 0)) {
    total_size += 1 + 4;
  }

  // int32 id = 7;
  if (this->_internal_id() != 0) {
    total_size += ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32SizePlusOne(this->_internal_id());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData PlayerInput_C_TO_S::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSizeCheck,
    PlayerInput_C_TO_S::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*PlayerInput_C_TO_S::GetClassData() const { return &_class_data_; }

void PlayerInput_C_TO_S::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to,
                      const ::PROTOBUF_NAMESPACE_ID::Message& from) {
  static_cast<PlayerInput_C_TO_S *>(to)->MergeFrom(
      static_cast<const PlayerInput_C_TO_S &>(from));
}


void PlayerInput_C_TO_S::MergeFrom(const PlayerInput_C_TO_S& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:Update_ShooterTest.PlayerInput_C_TO_S)
  GOOGLE_DCHECK_NE(&from, this);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_frameid() != 0) {
    _internal_set_frameid(from._internal_frameid());
  }
  if (from._internal_w() != 0) {
    _internal_set_w(from._internal_w());
  }
  if (from._internal_s() != 0) {
    _internal_set_s(from._internal_s());
  }
  if (from._internal_a() != 0) {
    _internal_set_a(from._internal_a());
  }
  if (from._internal_d() != 0) {
    _internal_set_d(from._internal_d());
  }
  if (!(from._internal_rotation() <= 0 && from._internal_rotation() >= 0)) {
    _internal_set_rotation(from._internal_rotation());
  }
  if (from._internal_id() != 0) {
    _internal_set_id(from._internal_id());
  }
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void PlayerInput_C_TO_S::CopyFrom(const PlayerInput_C_TO_S& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Update_ShooterTest.PlayerInput_C_TO_S)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool PlayerInput_C_TO_S::IsInitialized() const {
  return true;
}

void PlayerInput_C_TO_S::InternalSwap(PlayerInput_C_TO_S* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(PlayerInput_C_TO_S, id_)
      + sizeof(PlayerInput_C_TO_S::id_)
      - PROTOBUF_FIELD_OFFSET(PlayerInput_C_TO_S, frameid_)>(
          reinterpret_cast<char*>(&frameid_),
          reinterpret_cast<char*>(&other->frameid_));
}

::PROTOBUF_NAMESPACE_ID::Metadata PlayerInput_C_TO_S::GetMetadata() const {
  return ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(
      &descriptor_table_message_2eproto_getter, &descriptor_table_message_2eproto_once,
      file_level_metadata_message_2eproto[4]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace Update_ShooterTest
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::Update_ShooterTest::KcpWelcome_S_C* Arena::CreateMaybeMessage< ::Update_ShooterTest::KcpWelcome_S_C >(Arena* arena) {
  return Arena::CreateMessageInternal< ::Update_ShooterTest::KcpWelcome_S_C >(arena);
}
template<> PROTOBUF_NOINLINE ::Update_ShooterTest::PlayerInfo_S_TO_C* Arena::CreateMaybeMessage< ::Update_ShooterTest::PlayerInfo_S_TO_C >(Arena* arena) {
  return Arena::CreateMessageInternal< ::Update_ShooterTest::PlayerInfo_S_TO_C >(arena);
}
template<> PROTOBUF_NOINLINE ::Update_ShooterTest::UpdateInfo_S_TO_C* Arena::CreateMaybeMessage< ::Update_ShooterTest::UpdateInfo_S_TO_C >(Arena* arena) {
  return Arena::CreateMessageInternal< ::Update_ShooterTest::UpdateInfo_S_TO_C >(arena);
}
template<> PROTOBUF_NOINLINE ::Update_ShooterTest::KcpConnectReq_C_S* Arena::CreateMaybeMessage< ::Update_ShooterTest::KcpConnectReq_C_S >(Arena* arena) {
  return Arena::CreateMessageInternal< ::Update_ShooterTest::KcpConnectReq_C_S >(arena);
}
template<> PROTOBUF_NOINLINE ::Update_ShooterTest::PlayerInput_C_TO_S* Arena::CreateMaybeMessage< ::Update_ShooterTest::PlayerInput_C_TO_S >(Arena* arena) {
  return Arena::CreateMessageInternal< ::Update_ShooterTest::PlayerInput_C_TO_S >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
